version: '3'

services:
  din-springboot-container:
    image: din-spring-boot-docker-compose:2
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/din-springboot-container
    ports:
      - "8080-8100:8080"
