apiVersion: apps/v1
kind: Deployment
metadata:
  name: din-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: din-springboot
  template:
    metadata:
      labels:
        app: din-springboot
    spec:
      containers:
        - name: springboot
          image: dinik11/din-docker-demo:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: din-springboot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: din-springboot
